services:
  # Backend Service
  - type: web
    name: stock-alert-gh-backend
    env: go
    buildCommand: cd backend && go build -o main .
    startCommand: cd backend && ./main
    envVars:
      - key: PORT
        value: 10000
      - key: GO_ENV
        value: production
    healthCheckPath: /api/v1/health
    
  # Frontend Service  
  - type: web
    name: stock-alert-gh
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://stock-alert-gh-backend.onrender.com/api/v1
        
databases: []